export let usAutoforce = [
    "Bridgestone",
    "Continental",
    "Goodyear",
    "michelin",
    "Pirelli",
    "BFGoodrich",
    "CooperTires",
    "DunlopTires",
    "FalkenBlue",
    "Firestone",
    "GeneralTire",
    "Hankook",
    "KumhoTire",
    "Nitto",
    "Toyo",
    "Yokohama",
    "KellyTires",
    "KendaTires",
    "MastercraftTires",
    "MickeyThompson",
    "NexenTire",
    "RoadmasterTires",
    "Starfire",
    "Sumitomo",
    "Uniroyal",
    "Advanta",
    "Accelera",
    "Americus",
    "Delinte",
    "Carlisle",
    "Countrywide",
    "Towmax"
]

export let atd = [
    "Achilles",
    "Atturo",
    "BFGoodrich",
    "Continental",
    "Cooper",
    "Falken",
    "General",
    "GITI",
    "GT Radial",
    "Hankook",
    "Hercules",
    "Heritage",
    "Ironman",
    "Kumho",
    "Laufenn",
    "Mastercraft",
    "Michelin",
    "Mickey Thompson",
    "Milestar",
    "Nankang",
    "Nexen",
    "Nitto",
    "Ohtsu",
    "Paragon",
    "Pirelli",
    "Samson",
    "Toyo",
    "Uniroyal",
    "Vogue",
    "Yokohama",
    "Carlisle",
    "Dynamic",
    "Hi Run",
    "Super Cargo",
    "Sutong"
]
export const mfiConsumer =[
    "ADVANTA",
    "BFGOODRICH",
    "BRIDGESTONE",
    "CONTINENTAL",
    "Carlisle",
    "COOPER",
    "DUNLOPCONSUMER",
    "FALKEN",
    "FIRESTONE",
    "FUZION",
    "GENERAL",
    "GOODYEARCONSUMER",
    "HANKOOK",
    "KENDA",
    "KELLYCONSUMER",
    "KUMHOCONSUMER",
    "MICHELIN",
    "MICKEYTHOMPSON",
    "NEXEN",
    "NITTO",
    "OHTSU",
    "PIRELLI",
    "STARFIRE",
    "TOYO",
    "UNIROYAL",
    "YOKOHAMA",
    "TOWMAX"
]


export const ntw = [
    "Advance",
    "Antares",
    "Armadillo",
    "Aspen",
    "BFGoodrich",
    "BIG O",
    "BKT",
    "Bridgestone",
    "Caddiemaster",
    "Carlisle",
    "Carroll Tire",
    "Continental",
    "Cooper",
    "Cordovan",
    "Crosswind",
    "Deestone",
    "Delta",
    "Denman",
    "Doral",
    "Double Coin",
    "Dunlop",
    "Duraturn",
    "Duro",
    "Durun",
    "Dynacargo",
    "EL Dorado",
    "Eurogrip",
    "Falken",
    "Farm King",
    "Firestone",
    "General",
    "Gladiator",
    "Goodyear",
    "Hankook",
    "Harvest King",
    "Kelly Springfield",
    "Kenda",
    "Kleber",
    "Kumho",
    "Laufenn",
    "Mastercraft",
    "Maxxis",
    "Michelin",
    "Milestar",
    "Mitas",
    "Multi Mile",
    "Nankang",
    "National",
    "Nexen",
    "Nitto",
    "Nokian",
    "Non_Stock Tires (XP",
    "Pirelli",
    "Power King",
    "Prinx",
    "Provato",
    "Sailun",
    "Samson",
    "Saxon",
    "Sigma",
    "Solideal",
    "Specialty",
    "Sumitomo",
    "TBC Neutral",
    "Tempra",
    "Teton",
    "Tire Co",
    "Toyo",
    "Trelleborg",
    "Uniroyal",
    "Vogue",
    "Voma",
    "Wanda",
    "Yokohama",
    "Zenna"
]

export const tireRack = [
    "Avon",
    "BFGoodrich",
    "Bridgestone",
    "Continental",
    "Cooper",
    "Dunlop",
    "Falken",
    "Firestone",
    "Fuzion",
    "General Tire",
    "Goodyear",
    "Hankook",
    "Hoosier",
    "Kumho",
    "Laufenn",
    "Maxxis",
    "Michelin",
    "Mickey Thompson",
    "Nankang",
    "Nexen",
    "Nitto",
    "Pirelli",
    "Power King",
    "Riken",
    "Sumitomo",
    "Toyo",
    "Vogue Tyre",
    "Vredestein",
    "Yokohama"
]

export const tirehub = [
    "Bridgestone",
    "Goodyear",
    "Dunlop",
    "Firestone",
    "Fuzion",
    "Kelly",
    "Cooper",
    "Toyo",
    "Prinx",
    "Mickey Thompson"
]
